---

- name: "vault | check distribution compatibility"
  fail:
    msg: "{{ ansible_distribution }} is not supported by this role"
  when: ansible_distribution not in ['RedHat', 'CentOS', 'Fedora', 'Debian', 'Ubuntu', 'Archlinux']

- name: "vaullt | fail if not a new release of red hat / centos"
  fail:
    msg: "{{ ansible_distribution_version }} is not a supported version of {{ ansible_distribution }} for this role"
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - ansible_distribution_version is version(7, '<')

- name: "vault | fail if not a new release of debian"
  fail:
    msg: "{{ ansible_distribution_version }} is not a supported version of {{ ansible_distribution }} for this role"
  when:
    - ansible_distribution == "Debian"
    - (ansible_distribution_version != 'buster/sid') and (ansible_distribution_version is version(8.5, '<'))

- name: "vault | fail if not a new release of freebsd"
  fail:
    msg: "{{ ansible_distribution_version }} is not a supported version."
  when:
    - ansible_distribution == "FreeBSD"
    - ansible_distribution_version is version(10, '<')

- name: "vault | fail if not a new release of ubuntu"
  fail:
    msg: "{{ ansible_distribution_version }} is not a supported version of {{ ansible_distribution }} for this role"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version(13.04, '<')

- name: "vault | check for vault_redirect_address usage"
  debug:
    msg: "vault_redirect_address is deprecated. Check for vault_api_addr in the README."
  when: vault_redirect_address is defined
