---

- block:
    - name: "vault | add vault_addr environment variable in bashrc"
      lineinfile:
        path: "{{ vault_home }}/.bashrc"
        line: "export VAULT_ADDR='{{ vault_protocol }}://{{ vault_address }}:{{ vault_port }}'"
        create: true
        mode: "0644"

    - name: "vault | add vault_cacert environment variable in bashrc"
      lineinfile:
        path: "{{ vault_home }}/.bashrc"
        line: "export VAULT_CACERT={{ vault_tls_path.dst_path }}/{{ vault_tls_files.ca_file }}"
        create: true
        mode: "0644"
      when: "vault_tls_enable | bool()"

    - name: "vault | add vault_skip_verify environment variable in bashrc"
      lineinfile:
        path: "{{ vault_home }}/.bashrc"
        line: "export VAULT_SKIP_VERIFY=true"
        create: true
        mode: "0644"
      when:
        - "vault_tls_enable | bool()"
        - "vault_tls_sni.skip_verify | bool()"

    - name: "vault | add vault_tls_sni.server_name environment variable in bashrc"
      lineinfile:
        path: "{{ vault_home }}/.bashrc"
        line: "export vault_tls_sni.server_name={{ vault_tls_sni.server_name }}"
        create: true
        mode: "0644"
      when:
        - "vault_tls_enable | bool()"
        - "vault_tls_sni.server_name is defined and vault_tls_sni.server_name"
  become: true
  become_user: "{{ vault_user }}"
