---

- name: "vault | add vault_addr environment variable in bashrc"
  lineinfile:
    path: "{{ vault_home }}/.bashrc"
    line: "export VAULT_ADDR='{{ vault_tls_disable | ternary('http', 'https') }}://{{ vault_address }}:{{ vault_port }}'"
    create: true
    mode: 0644

- name: "vault | add vault_cacert environment variable in bashrc"
  lineinfile:
    path: "{{ vault_home }}/.bashrc"
    line: "export VAULT_CACERT={{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    create: true
    mode: 0644
  when: "not vault_tls_disable | bool()"
