---

- block:
    - name: "vault | add yum repository"
      yum_repository:
        name: "vault"
        baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
        gpgkey: "https://rpm.releases.hashicorp.com/gpg"
        gpgcheck: true
        state: "present"

    - name: "vault | install vault via yum"
      yum:
        name: "vault-{{ vault_version }}"
        state: "present"
        update_cache: true
  when: "ansible_pkg_mgr == 'yum'"

- block:
    - name: "vault | add hashicorp apt signing key"
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: "present"

    - name: "vault | add hashicorp apt repo"
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: "present"
        update_cache: true

    - name: "vault | install vault via apt"
      apt:
        name: vault={{ vault_version }}
  when: "ansible_pkg_mgr == 'apt'"
