---

- block:
    - name: "vault | check vault package checksum file (local)"
      stat:
        path: "{{ role_path }}/files/{{ vault_shasums }}"
      run_once: true
      register: "vault_checksum"

    - name: "vault | get vault package checksum file (local)"
      get_url:
        url: "{{ vault_checksum_file_url }}"
        dest: "{{ role_path }}/files/{{ vault_shasums }}"
        mode: "0600"
      run_once: true
      when: "not vault_checksum.stat.exists | bool()"

    - name: "vault | get vault package checksum (local)"
      shell: |
        set -o pipefail
        grep "{{ vault_pkg }}" "{{ role_path }}/files/{{ vault_shasums }}" | \
        awk '{print $1}'
      args:
        executable: "/bin/bash"
      run_once: true
      register: "vault_sha256"
      tags: "skip_ansible_lint"

    - name: "vault | check vault package file (local)"
      stat:
        path: "{{ role_path }}/files/{{ vault_pkg }}"
      run_once: true
      register: "vault_package"

    - name: "vault | download vault (local) → {{ vault_zip_url }}"
      get_url:
        url: "{{ vault_zip_url }}"
        dest: "{{ role_path }}/files/{{ vault_pkg }}"
        checksum: "sha256:{{ vault_sha256.stdout }}"
        timeout: 42
        mode: "0600"
      run_once: true
      when: "not vault_package.stat.exists | bool()"

    - name: "vault | unarchive vault (local)"
      unarchive:
        src: "{{ role_path }}/files/{{ vault_pkg }}"
        dest: "{{ role_path }}/files/"
        creates: "{{ role_path }}/files/vault"
        mode: "0755"
      run_once: true
  become: false
  delegate_to: "localhost"

- name: "vault | ensure vault is stopped before upgrade"
  service:
    name: "{{ vault_systemd_service_name }}"
    state: "stopped"
  when: "vault_upgrade_inplace | bool()"

- name: "vault | install vault (local)"
  become: true
  copy:
    src: "{{ role_path }}/files/vault"
    dest: "{{ vault_bin_path }}"
    force: "{{ vault_upgrade_inplace | default(omit) }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: "vault | cleanup (local)"
  become: false
  file:
    path: "{{ item }}"
    state: "absent"
  with_fileglob: "{{ role_path }}/files/vault"
  run_once: true
  delegate_to: "localhost"
