---

- block:
    - name: "vault | add vault group"
      group:
        name: "{{ vault_group }}"
        state: present
      when: vault_manage_group | bool()

    - name: "vault | add vault user"
      user:
        name: "{{ vault_user }}"
        comment: "vault dedicated user"
        group: "{{ vault_group }}"
        groups: "{{ vault_groups | default(omit) }}"
        system: true
        shell: "/bin/bash"
      when: vault_manage_user | bool()

    - name: "vault | create directories"
      file:
        dest: "{{ item.path }}"
        state: "directory"
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        mode: "{{ item.mode | default('0755') | int() }}"
      loop:
        - path: "{{ vault_config_path }}"
        - path: "{{ vault_plugin_path }}"
        - path: "{{ vault_data_path }}"
        - path: "{{ vault_log_path }}"
        - path: "{{ vault_run_path }}"

    - name: "vault | install vault dependencies"
      package:
        name: "{{ vault_os_packages }}"
        state: "present"

    - name: "vault | enable logrotate"
      template:
        src: "{{ vault_logrotate_template }}"
        dest: "/etc/logrotate.d/vault"
        owner: "root"
        group: "root"
        mode: 0644
      when: "vault_enable_logrotate | bool()"

    - name: "vault | set exec output to log path when enabled log"
      set_fact:
        vault_exec_output: "2>&1 >> {{ vault_log_path }}/vault.log"
      when: "vault_enable_log"
  become: true
