---

- name: "vault | create tls directory"
  become: true
  file:
    dest: "{{ vault_tls_path.dst_path }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0755"

- name: "vault | vault ssl certificate and key"
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: "{{ vault_tls_path.src_remote | default(omit) }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ vault_tls_path.src_path }}/{{ vault_tls_files.cert_file }}"
      dest: "{{ vault_tls_path.dst_path }}/{{ vault_tls_files.cert_file }}"
      mode: "0440"
    - src: "{{ vault_tls_path.src_path }}/{{ vault_tls_files.key_file }}"
      dest: "{{ vault_tls_path.dst_path }}/{{ vault_tls_files.key_file }}"
      mode: "0440"
    - src: "{{ vault_tls_path.src_path }}/{{ vault_tls_files.ca_file }}"
      dest: "{{ vault_tls_path.dst_path }}/{{ vault_tls_files.ca_file }}"
      mode: "0440"
  when: "vault_tls_files.copy | bool()"
  no_log: true
