---

- name: "vault | create tls directory"
  become: true
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
  loop:
    - "{{ vault_tls_config_path }}"

- name: "vault | vault ssl certificate and key"
  become: true
  copy:
    remote_src: "{{ vault_tls_files_remote_src }}"
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ item.mode }}"
  loop:
    - src: "{{ vault_tls_src_files }}/{{ vault_tls_cert_file }}"
      dest: "{{ vault_tls_config_path }}/{{ vault_tls_cert_file }}"
      mode: 0644
    - src: "{{ vault_tls_src_files }}/{{ vault_tls_key_file }}"
      dest: "{{ vault_tls_config_path }}/{{ vault_tls_key_file }}"
      mode: 0600
    - src: "{{ vault_tls_src_files }}/{{ vault_tls_ca_file }}"
      dest: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
      mode: 0644
  when: "vault_tls_copy_keys | bool()"
