---

- name: "restart vault"
  become: true
  service:
    name: "{{ vault_systemd_service_name }}"
    state: "restarted"

- name: "daemon-reload systemd"
  become: true
  systemd:
    daemon-reload: true
